### ISSUE TITLE
Would like to join this project

### ISSUE THREAD

**Issue by roman-shuhov** [fsprojects/Mechanic#11]
I can call myself a newcomer in F# world and this sounds as a great idea!

**Comment by forki** [comment]
awesome. welcome aboard

**Comment by fbehrens** [comment]
I like to join, had some experience with `F#` but are kind of new and struggling with `.NET Core`.

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with. There's a couple of ongoing discussions on how to structure the library, and especially #10 has some details on where the code base might be heading.
