### ISSUE TITLE
Reenable Travis and Appveyor after Project rename

### ISSUE THREAD

**Issue by fbehrens** [fsprojects/Mechanic#25]
To me it looks like the CI is gone.
Before the rename I could see the builds in the commits.

**Comment by tlycken** [comment]
Good catch!

Travis seems to have auto-updated, but I created a new Appveyor project pointing to the right place now (and deleted the old one). New PR's should start seeing the build reports again.

**Comment by fbehrens** [comment]
Thanks,

by the way:
I was looking wrong. Now I see the CI details only appear in the PR section.
