### ISSUE TITLE
Count me in!

### ISSUE THREAD

**Issue by eriawan** [fsprojects/Mechanic#27]
@forki 

I'd like to join, collaborate and participate as well. I may not be quite visible or known in F# community, but basically I just want to get my feet wet quickly for this tool 🙂

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with. There's a couple of ongoing discussions on how to structure the library, and especially #10 has some details on where the code base might be heading.
