### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by JohnStov** [fsprojects/Mechanic#29]
Count me in! Happy to help out with this.

I cloned the project in Ubuntu and ran `./src/build.sh --use-mono`. Everything built fine,

Cloned in Windows, ran `.\src\build.cmd` and got several errors.  It's not obvious to me what the problem is.

I can post the output here if people want to see it.

**Comment by jpierson** [comment]
The PowerShell script worked for me on win10. Not sure if dotnet SDK is prerequisite but I probably already had it installed as well as F# tools.

**Comment by JohnStov** [comment]
paket updated to 5.129.0.
Now builds successfully and runs tests, but reports an error before exiting.
Same result with .cmd & .ps1

**Comment by forki** [comment]
What error?

**Comment by JohnStov** [comment]
Problem solved - Once I deleted the project and recloned it, the problem went away.

May have been an issue with an old version of paket, but not worth further investigation.
