### ISSUE TITLE
I'd like to help as well

### ISSUE THREAD

**Issue by chicocode** [fsprojects/Mechanic#39]
Hello guys, I'd like to help, the project looks amazing! But how to start? Looks like there are lot of things to do, but don't know with what I can start.

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with. There's a couple of ongoing discussions on how to structure the library, and especially #10 has some details on where the code base might be heading.
