### ISSUE TITLE
I would like to join the project

### ISSUE THREAD

**Issue by jasondown** [fsprojects/Mechanic#51]
Hello folks,

I've been a long-time C# and (until about a year ago) Dynamics NAV programmer who has been exploring F# for a couple of years on my own time. I'm really eager to work on a real project in F# (particularly OSS since I've never done that before either). This would fit in great with the #100DaysOfCode challenge I started last week (my first week has been devoted to learning FSharp.Data and FSharp.Charting).

I would say my F# skills are at the high end of beginner. However, I have little to no experience with the tooling, outside of Visual Studio and FSI. I suspect that part of the point of this project is to help people like me improve in this area, while also helping the community out.

So if you'll have me, I'd love to join the team.

Thanks,
Jason

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with.
