### ISSUE TITLE
Saving new order of source files to project file 

### ISSUE THREAD

**Issue by jindraivanek** [fsprojects/Mechanic#62]
Potential problems:
* what to do with other than source file items, do we want to merge their order, or move them down?
* paths that using msbuild properties

**Comment by forki** [comment]
hey @jindraivanek, @MangelMaxime has an vscode plugin prototype ready. Any chance you could do a bit of this front here? 

What I think we need right now is a command line switch for mechanic that actually saves the order to the fsproj. the spupidest thing that could work would help right now.

**Comment by jindraivanek** [comment]
Great! Saving fsproj works right now when you call Mechanic with one argument (path to fsproj).

**Comment by forki** [comment]
Awesome

**Comment by MangelMaxime** [comment]
@jindraivanek Thanks for the info, I need to check on a clean fsproj then :)

**Comment by jindraivanek** [comment]
This is partially done, closing in favor of #85.
