### ISSUE TITLE
I'm happy to help

### ISSUE THREAD

**Issue by markpattison** [fsprojects/Mechanic#8]
I have experience with FAKE/Paket and a bit with the dotnet cli.

**Comment by forki** [comment]
cool. welcome aboard!

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with. There's a couple of ongoing discussions on how to structure the library, and especially #10 has some details on where the code base might be heading.
