### ISSUE TITLE
I would like to contribute as well

### ISSUE THREAD

**Issue by swrhim** [fsprojects/Mechanic#9]
I saw that @eiriktsarpalis posted your tweet on our slack channel and I would like to help. I'm all for adding more tooling for F#!

**Comment by forki** [comment]
cool! welcome aboard!

**Comment by tlycken** [comment]
Welcome! I suggest taking a look at the list of issues to see if there is anything there you feel like you'd like to contribute with. There's a couple of ongoing discussions on how to structure the library, and especially #10 has some details on where the code base might be heading.
