### ISSUE TITLE
Tests fail when run in ionide-mechanic

### ISSUE THREAD

**Issue by forki** [fsprojects/Mechanic#96]
@jindraivanek 

![image](https://user-images.githubusercontent.com/57396/37582379-f9a39124-2b4c-11e8-9c0e-229ee951e17e.png)

**Comment by forki** [comment]
any ideas?

**Comment by forki** [comment]
ok same test errors  if I run in this repo on my machine

    System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden

System can't find the file

**Comment by jindraivanek** [comment]
Yeah, tests are looking for project templates in `templates` dir. Didn't realize that we are running tests also outside root dir. Any good standard way how to find this dir?

**Comment by forki** [comment]
As I said: it also fails on my fork of this repo here

**Comment by jindraivanek** [comment]
Also when ran from Mechanic root folder?

**Comment by forki** [comment]
Yes. Running build.fsx from my mechanic root. But I'm wondering if it's missing something else. Like a MSBuild exe or something. Unfortunately it doesn't trace what it needs

**Comment by jindraivanek** [comment]
Ah, yes, now I see it in stack trace. Sorry.. Looks like its about missing `msbuild`. Maybe ProjectCracker relies on `msbuild` in path.
